import React from 'react';
import Sidebar from '../components/sidebar/Sidebar'; // Adjust the import path as needed
import { Grid, GridItem, PageSection, Card, CardTitle, CardBody, TextContent, Text, TextVariants, TextList, TextListVariants, TextListItem} from '@patternfly/react-core';
import './Introduction.css'

function ImplementationPage() {
  return (
    <div style={{ display: 'flex', backgroundColor: '#f0f0f0'}} className='page-container'>
      <div className="main-content-container">
      <Sidebar />
      <main style={{ flexGrow: 1, padding: '1rem' }} className='main-content'> {/* Main content */}
      <TextContent style={{ marginRight:'200px', marginLeft:'8px'}}>
        <Text component={TextVariants.h1} style={{ fontSize: '36px', marginBottom: '48px'}}>5G Implementation Overview</Text>
        
        <div style={{ display: 'flex', justifyContent: 'center' }}>
          <img src="/arsitektur.png" alt="arsitektur" style={{ marginBottom: '24px', width: '650px'}}/>
        </div>

        <Text component={TextVariants.h1} style={{ fontSize: '28px'}}>5G Core Network</Text>
        <Text component={TextVariants.p}>
          The 5G Core Network is the backbone of the modern mobile communications system. 
          It supports various services and ensures seamless connectivity and data transmission.
        </Text>

        <Text component={TextVariants.h3}>Components and Their Functions</Text>
        <TextList component={TextListVariants.ol}>
          <TextListItem>Access and Mobility Management Function (AMF): Manages user equipment (UE) access and mobility.</TextListItem>
          <TextListItem>Session Management Function (SMF): Handles session management and IP address allocation.</TextListItem>
          <TextListItem>User Plane Function (UPF): Manages the user plane traffic and routing.</TextListItem>
          <TextListItem>Network Repository Function (NRF): Maintains a repository of network functions and their profiles.</TextListItem>
          <TextListItem>Policy Control Function (PCF): Enforces network policies.</TextListItem>
          <TextListItem>Unified Data Management (UDM): Manages user data and profiles.</TextListItem>
        </TextList>

        <Text component={TextVariants.h3}>Log Components</Text>
        <Text component={TextVariants.p} style={{marginBottom: '48px'}}>
          Understanding the logs generated by each component is crucial for troubleshooting and optimization. 
          Each log entry provides insights into the component's operations, performance, and any issues encountered.
        </Text>

        <Text component={TextVariants.h1} style={{ fontSize: '28px'}}>Open Radio Access Network</Text>
        <Text component={TextVariants.p}>
          Open RAN revolutionizes traditional RAN architecture by promoting interoperability 
          and flexibility through open interfaces and standards.
        </Text>

        <Text component={TextVariants.h3}>Components and Their Functions</Text>
        <TextList component={TextListVariants.ol}>
          <TextListItem>Central Unit (CU): Controls the radio network, manages signaling, and processes data.</TextListItem>
          <TextListItem>Distributed Unit (DU): Handles real-time processing and radio signal management.</TextListItem>
          <TextListItem>Radio Unit (RU): Converts digital signals to radio waves and vice versa, interfacing with the antennas.</TextListItem>
        </TextList>

        <Text component={TextVariants.h3}>Log Interpretations</Text>
        <Text component={TextVariants.p} style={{marginBottom: '48px'}}>
          Logs from Open RAN components offer detailed information about the performance, issues, and interactions 
          between CUs, DUs, and RUs, facilitating effective network management.
        </Text>
      </TextContent>
      </main>
      </div>
    </div>
  );
}

export default ImplementationPage;



